---
name: Latexmk

on: [push]

jobs:
  build:
    defaults:
       run:
        working-directory: research_cv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.1.0
        with:
          format: pdf
          filename: main.tex
          
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit files
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "<>"
          git commit -m "Add main.pdf changes" main.pdf
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
